spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:55434/gamificacao}
spring.datasource.username=${DATABASE_USER:gamificacao}
spring.datasource.password=${DATABASE_PASSWORD:gamificacao_dev}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=false
